---

services:

  rustfs:
    image: rustfs/rustfs:latest
    env_file:
      - .env
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: ${RUSTFS_CONSOLE_ENABLE:-true}
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY:-rustfsadmin}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY:-rustfsadmin}
      RUSTFS_OBS_LOGGER_LEVEL: info
      RUSTFS_OBS_ENDPOINT: ${RUSTFS_OBS_ENDPOINT:-http://otel-collector:4318}
      RUSTFS_OBS_SERVICE_NAME: ${RUSTFS_OBS_SERVICE_NAME:-rustfs}
      RUSTFS_OBS_ENVIRONMENT: ${RUSTFS_OBS_ENVIRONMENT:-local}
      RUSTFS_OBS_METRICS_EXPORT_ENABLED: ${RUSTFS_OBS_METRICS_EXPORT_ENABLED:-true}
      RUSTFS_OBS_LOGS_EXPORT_ENABLED: ${RUSTFS_OBS_LOGS_EXPORT_ENABLED:-true}
      RUSTFS_OBS_TRACES_EXPORT_ENABLED: ${RUSTFS_OBS_TRACES_EXPORT_ENABLED:-false}
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_UNSAFE_BYPASS_DISK_CHECK: ${RUSTFS_UNSAFE_BYPASS_DISK_CHECK:-false}
    volumes:
      - application-rustfs:/data
    networks:
      - rustfs
      - app_traefik_reverse-proxy
      - app_monitoring_monitoring
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "sh", "-ec", "curl -fsS http://127.0.0.1:9000/health && curl -fsS http://127.0.0.1:9001/rustfs/console/health"]
      interval: 30s
      start_period: 40s
      retries: 3
      timeout: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.swarm.network=app_traefik_reverse-proxy
        - traefik.http.services.rustfs-s3.loadbalancer.server.port=9000
        - traefik.http.services.rustfs-s3.loadbalancer.passhostheader=true
        - traefik.http.routers.rustfs-s3.rule=Host(`${RUSTFS_HOST:-s3.localhost}`)
        - traefik.http.routers.rustfs-s3.service=rustfs-s3
        - traefik.http.services.rustfs-console.loadbalancer.server.port=9001
        - traefik.http.services.rustfs-console.loadbalancer.passhostheader=true
        - traefik.http.routers.rustfs-console.rule=Host(`${RUSTFS_CONSOLE_HOST:-rustfs.localhost}`)
        - traefik.http.routers.rustfs-console.service=rustfs-console


networks:
  rustfs:
    name: app_rustfs_rustfs
    driver: overlay
    attachable: true
  app_traefik_reverse-proxy:
    external: true
  app_monitoring_monitoring:
    external: true


volumes:
  application-rustfs:
    driver: local
