---

services:

  keydb:
    image: 'eqalpha/keydb:latest'
    env_file:
      - .env
    volumes:
      - 'application-keydb:/data'
    networks:
      - keydb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  keydb:
    name: app_keydb_keydb
    driver: overlay
    attachable: true


volumes:
  application-keydb:
    driver: local